swagger: "2.0"
info:
    version: "1.0"
    title: "Booking avbl"

paths:
    /catalog:
        get:
            responses:
              400:
                description: "Route error"
              200:
                description: "Fetch rooms"
                schema:
                  properties:
                    rooms:
                        type: array
                        items:
                            type: object
                            properties:
                                roomId:
                                    type: integer
                                address_hotel:
                                    type: string
                                category:
                                    type: string
                                price:
                                    type: number
                                hotelId:
                                    type: integer
                    
              500:
                description: "Internal error"
    
    /book:
        get:
            parameters:
              - name: body
                in: body
                required: true
                schema:
                  properties:
                    token:
                      type: string
                    roomId:
                        type: number
                      
            responses:
              400:
                description: "Invalid request"
              200:
                description: "liste des dates reserve pour cette chambre"
                schema:
                  properties:
                    dates:
                        type: array
                        items:
                            type: string
                            format: date
              500:
                description: "Internal error"
                
        post:
            parameters:
              - name: body
                in: body
                required: true
                schema:
                  properties:
                    token:
                      type: string
                    roomId:
                        type: number
                    startDate:
                        type: string
                    endDate:
                        type: string
                    garage:
                        type: boolean
                    litbebe:
                        type: boolean
                    petitdej:
                        type: boolean
                    nomClient:
                        type: string
                    prenomClient:
                        type: string
                    mail:
                        type: string
                      
            responses:
              400:
                description: "Invalid request"
              200:
                description: "Reservation reussi"
              500:
                description: "Internal error"
                
    /price:
        get:
            parameters:
              - name: body
                in: body
                required: true
                schema:
                  properties:
                    token:
                        type: string
                    roomId:
                        type: integer
                    categoryId:
                        type: integer
                      
            responses:
              400:
                description: "get price error"
              200:
                description: "get room price"
                schema:
                  properties:
                    price:
                        type: number
              500:
                description: "Internal error"
                
    /mail:
        post:
            parameters:
              - name: body
                in: body
                required: true
                schema:
                  properties:
                    email:
                        type: string
                    message:
                        type: string
                      
            responses:
              400:
                description: "Change base price error"
              200:
                description: "Base room price changed"
              500:
                description: "Internal error"
                
    /register_user:
        post:
            parameters:
              - name: body
                in: body
                required: true
                schema:
                  properties:
                    email:
                      type: string
                    lastname:
                        type: string
                    firstname:
                        type: string
                    password:
                        type: string
                    admin:
                        type: boolean
                      
            responses:
              200:
                description: "Create new user"
              400:
                description: "User not found"
              500:
                description: "Internal error"
                
    /login_user:
        post:
            parameters:
              - name: body
                in: body
                required: true
                schema:
                  properties:
                    email:
                      type: string
                    password:
                      type: string
                      
            responses:
              400:
                description: "User not found or id/password invalid"
              200:
                description: "User connected"
                schema:
                  properties:
                    token:
                        type: string
              500:
                description: "Internal error"
                
    /catalog/room:
        post:
            parameters:
              - name: body
                in: body
                required: true
                schema:
                  properties:
                    hotelId:
                      type: integer
                    categoryId:
                      type: integer
                    litbebe:
                        type: integer
                    parking:
                        type: integer

            responses:
              400:
                description: "erreur ajout chambre"
              200:
                description: "Chambre ajoute"
                    
              500:
                description: "Internal error"
                
    /catalog/hotel:
        post:
            parameters:
              - name: body
                in: body
                required: true
                schema:
                  properties:
                    name:
                      type: string
                    address:
                      type: string

            responses:
              400:
                description: "erreur ajout hotel"
              200:
                description: "Hotel ajoute"
                    
              500:
                description: "Internal error"

    /price/room:
        patch:
            parameters:
              - name: body
                in: body
                required: true
                schema:
                  properties:
                    token:
                        type: string
                    roomId:
                        type: integer
                    newPrice:
                        type: number
                      
            responses:
              400:
                description: "Change base price error"
              200:
                description: "Base room price changed"
              500:
                description: "Internal error"
                
    /price/increase:
        patch:
            parameters:
              - name: body
                in: body
                required: true
                schema:
                  properties:
                    token:
                        type: string
                    days:
                        type: array
                        items:
                            type: string
                    percentage:
                        type: number
                      
            responses:
              400:
                description: "Price percent change fail"
              200:
                description: "Price coeff changed"
              500:
                description: "Internal error"
