- name: pull chronograf
  become: true
  docker_image:
    name: chronograf

- name: Tag chronograf
  become: true
  command: docker tag chronograf myregistry.com:5000/chronograf

- name: Push chronograf to local registry
  become: true
  command: docker push myregistry.com:5000/chronograf

- name: pull influxdb
  become: true
  docker_image:
    name: influxdb

- name: Tag influxdb
  become: true
  command: docker tag influxdb myregistry.com:5000/influxdb

- name: Push influxdb to local registry
  become: true
  command: docker push myregistry.com:5000/influxdb

- name: pull kapacitor
  become: true
  docker_image:
    name: kapacitor

- name: Tag kapacitor
  become: true
  command: docker tag kapacitor myregistry.com:5000/kapacitor

- name: Push kapacitor to local registry
  become: true
  command: docker push myregistry.com:5000/kapacitor

- name: pull telegraf
  become: true
  docker_image:
    name: telegraf

- name: Tag telegraf
  become: true
  command: docker tag telegraf myregistry.com:5000/telegraf

- name: Push telegraf to local registry
  become: true
  command: docker push myregistry.com:5000/telegraf