Route
---
parameters:
  - name: body
    in: body
    required: true
    schema:
      properties:
        token:
          type: string
          
responses:
  200:
    description: "Check if user user logged"
