Route
---
parameters:
  - name: body
    in: body
    required: true
    schema:
      properties:
        email:
          type: string
        password:
            type: string
          
responses:
  200:
    description: "Login user"
