Route
---
parameters:
  - name: body
    in: body
    required: true
    schema:
      properties:
        email:
          type: string
        lastname:
            type: string
        firstname:
            type: string
        password:
            type: string
        admin:
            type: boolean
          
responses:
  200:
    description: "Create new user"
  400:
    description: "User not found"
  500:
    description: "Internal error"
