version: '2.2'
networks:
  main:
  
services:
  auth:
    image: debian
    container_name: devops_auth
    restart: always
    volumes:
      - ./service_auth:/devops/service_auth
      - ./scripts:/devops/scripts
    ports:
      - 3000:3000
    command: /devops/scripts/run.sh /devops/service_auth api.py
    networks:
      main:
        aliases:
          - auth

  catalog:
    image: debian
    container_name: devops_catalog
    restart: always
    volumes:
      - ./service_catalog:/devops/service_catalog
      - ./scripts:/devops/scripts
    ports:
      - 4000:4000
    command: /devops/scripts/run.sh /devops/service_catalog api.py
    networks:
      main:
        aliases:
          - catalog

  gateway:
    image: debian
    container_name: devops_gateway
    restart: always
    volumes:
      - ./traefik:/devops/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 80:80
    command: /devops/traefik/traefik_linux-amd64 -c /devops/traefik/traefik.toml
    networks:
      main:
        aliases:
          - gateway



  mysql:
    image: mysql
    container_name: devops_mysql
    volumes:
      - ./mysql/etc/:/etc/mysql/mysql.conf.d/
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log:/var/log/mysql
      - ./mysql/backup:/backup
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: "devops"
      MYSQL_PASSWORD: "devops"
      MYSQL_DATABASE: "DEVOPS"
    networks:
      main:
        aliases:
          - mysql
