version: '2.2'
networks:
  main:
  
services:
  auth:
    image: debian
    container_name: devops_service_auth
    restart: always
    volumes:
      - ./service_auth:/devops/service_auth
      - ./scripts:/devops/scripts
    ports:
      - 3000:3000
    command: /devops/scripts/run.sh /devops/service_auth api.py
    networks:
      main:
        aliases:
          - auth

  catalog:
    image: debian
    container_name: devops_service_catalog
    restart: always
    volumes:
      - ./service_catalog:/devops/service_catalog
      - ./scripts:/devops/scripts
    ports:
      - 4000:4000
    command: /devops/scripts/run.sh /devops/service_catalog api.py
    networks:
      main:
        aliases:
          - catalog

  price:
    image: debian
    container_name: devops_service_price
    restart: always
    volumes:
      - ./service_price:/devops/service_price
      - ./scripts:/devops/scripts
    ports:
      - 5000:5000
    command: /devops/scripts/run.sh /devops/service_price api.py
    networks:
      main:
        aliases:
          - price



  gateway:
    image: debian
    container_name: devops_gateway
    restart: always
    volumes:
      - ./traefik:/devops/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 80:80
    command: /devops/traefik/traefik_linux-amd64 -c /devops/traefik/traefik.toml
    networks:
      main:
        aliases:
          - gateway

    networks:
      main:
        aliases:
          - mysql_auth
