version: '2.2'
networks:
  main:
  internal:
  
services:
  auth:
    image: debian
    container_name: devops_service_auth
    restart: always
    volumes:
      - ./service_auth:/devops/service_auth
      - ./scripts:/devops/scripts
    ports:
      - 3000:3000
    command: /devops/scripts/run.sh /devops/service_auth api.py 3000
    networks:
      main:
        aliases:
          - auth

  catalog:
    image: debian
    container_name: devops_service_catalog
    restart: always
    volumes:
      - ./service_catalog:/devops/service_catalog
      - ./scripts:/devops/scripts
    ports:
      - 3100:3100
    command: /devops/scripts/run.sh /devops/service_catalog api.py 3100
    networks:
      main:
        aliases:
          - catalog

  price:
    image: debian
    container_name: devops_service_price
    restart: always
    volumes:
      - ./service_price:/devops/service_price
      - ./scripts:/devops/scripts
    ports:
      - 3200:3200
    command: /devops/scripts/run.sh /devops/service_price api.py 3200
    networks:
      main:
        aliases:
          - price

  book:
    image: debian
    container_name: devops_service_booking
    restart: always
    volumes:
      - ./service_booking:/devops/service_booking
      - ./scripts:/devops/scripts
    ports:
      - 3300:3300
    command: /devops/scripts/run.sh /devops/service_booking api.py 3300
    networks:
      main:
        aliases:
          - booking
      internal:
        aliases:
          - booking


  gateway:
    image: debian
    container_name: devops_gateway
    restart: always
    volumes:
      - ./traefik:/devops/traefik
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
      - 80:80
    command: /devops/traefik/traefik_linux-amd64 -c /devops/traefik/traefik.toml
    networks:
      main:
        aliases:
          - gateway

