Route
---
parameters:
  - name: body
    in: body
    required: true
    schema:
      properties:
        token:
            type: string
        days:
            type: array
            items:
                type: string
        percentage:
            type: number
          
responses:
  400:
    description: "Price percent change fail"
  200:
    description: "Price coeff changed"
  500:
    description: "Internal error"
