Route
---
parameters:
  - name: body
    in: body
    required: true
    schema:
      properties:
        token:
            type: string
        roomId:
            type: integer
        newPrice:
            type: number
          
responses:
  400:
    description: "Change base price error"
  200:
    description: "Base room price changed"
  500:
    description: "Internal error"
