- name: Import crt
  become: true
  copy:
    src: ../../provision/domain.crt
    dest: /usr/local/share/ca-certificates

- name: Import key
  become: true
  copy:
    src: ../../provision/domain.key
    dest: /usr/local/share/ca-certificates

- name: Add domain myregistry.com on ip of the swarm manager
  become: true
  lineinfile:
    dest: /etc/hosts
    line: "172.16.226.17 myregistry.com"
    state: present

- name: Import daemon.json
  become: true
  copy:
    src: ../../provision/daemon.json
    dest: /etc/docker/

- name: Restart docker service
  become: true
  command: /etc/init.d/docker restart

- name: Check if container is running
  become: true
  shell: docker ps
  register: containers

- name: Deploy registry
  become: true
  when: inventory_hostname in groups['manager']
  ignore_errors: yes
  shell: >
    docker service create --name registry --publish=5000:5000 \
     --constraint=node.role==manager \
     --mount=type=bind,src=/home/docker,dst=/certs \
     -e REGISTRY_HTTP_ADDR=0.0.0.0:5000 \
     registry:latest