- name: Change hostname
  become: true
  command: echo "172.16.226.17 myregistry.com" >> /etc/hosts

- name: Import daemon.json
  become: true
  copy:
    src: ../../provision/daemon.json
    dest: /etc/docker/

- name: Check if container is running
  become: true
  shell: docker ps
  register: containers

- name: Deploy registry
  become: true
  when: inventory_hostname in groups['manager']
  ignore_errors: yes
  shell: >
    docker service create --name registry --publish=5000:5000 \
     --constraint=node.role==manager \
     --mount=type=bind,src=/home/docker,dst=/certs \
     -e REGISTRY_HTTP_ADDR=0.0.0.0:5000 \
     registry:latest