Route
---
parameters:
  - name: body
    in: body
    required: true
    schema:
      properties:
        token:
          type: string
        roomId:
            type: number
          
responses:
  400:
    description: "Invalid request"
  200:
    description: "liste des dates reserve pour cette chambre"
    schema:
      properties:
        dates:
            type: array
            items:
                type: string
  500:
    description: "Internal error"
    
