docker_apt_key: '9DC858229FC7DD38854AE2D88D81803C0EBFCD88'
docker_distribution: '{{ ansible_local.core.distribution
                         if (ansible_local|d() and ansible_local.core|d() and
                             ansible_local.core.distribution|d())
                         else ansible_distribution }}'
docker_distribution_release: '{{ ansible_local.core.distribution_release
                                 if (ansible_local|d() and ansible_local.core|d() and
                                     ansible_local.core.distribution_release|d())
                                 else ansible_distribution_release }}'

# Address of the Docker repository.
docker_repository: 'deb [arch=amd64] https://download.docker.com/linux/{{ docker_distribution | lower }} {{ docker_distribution_release }} stable'
docker_apt_source: 'https://download.docker.com/linux/{{ docker_distribution | lower }}/gpg'
manager: 172.16.226.17